"""Add timestamp to Game model.

Revision ID: 262a37c2e2f8
Revises: de5608e54571
Create Date: 2020-07-02 14:23:14.928957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262a37c2e2f8'
down_revision = 'de5608e54571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_games_timestamp'), 'games', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_timestamp'), table_name='games')
    op.drop_column('games', 'timestamp')
    # ### end Alembic commands ###
