"""Add display column in Drawing model.

Revision ID: a51432d2e907
Revises: 262a37c2e2f8
Create Date: 2020-07-03 10:28:48.375427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51432d2e907'
down_revision = '262a37c2e2f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawings', sa.Column('display', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drawings', 'display')
    # ### end Alembic commands ###
