"""Add timestamp columnto Drawing model.

Revision ID: de5608e54571
Revises: 00424e7531a0
Create Date: 2020-07-02 14:17:00.825652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de5608e54571'
down_revision = '00424e7531a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawings', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_drawings_timestamp'), 'drawings', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drawings_timestamp'), table_name='drawings')
    op.drop_column('drawings', 'timestamp')
    # ### end Alembic commands ###
