"""Implement friendship functionality to User model.

Revision ID: fd90b9dac1bd
Revises: a51432d2e907
Create Date: 2020-07-04 00:56:12.108696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd90b9dac1bd'
down_revision = 'a51432d2e907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('not_confirmed', 'confirmed'), server_default='not_confirmed', nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('inviter_games_won', sa.Integer(), nullable=True),
    sa.Column('invitee_games_won', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('inviter_id', 'invitee_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendships')
    # ### end Alembic commands ###
